baseURL = 'https://jflores-deinew.github.io/thisisJairo.github.io/'
title = "Jairo Flores"
theme ='ananke'
languageCode = "es"
DefaultContentLanguage = "es"
paginate = 3
SectionPagesMenu = "main"
googleAnalytics = ""
enableRobotsTXT = false
canonifyURLs = false  # Desactivado para evitar problemas con las URLs relativas

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "Página personal de Jairo Flores, apasionado por la programación competitiva y C++."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Jflores-deinew"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jairoflorespereyra/"
  mastodon = ""
  slack = ""
  codeforces = ""
  stackoverflow = ""

