baseURL = 'https://example.org/'
title = "Jairo Flores"
theme = 'ananke'
languageCode = "es"
DefaultContentLanguage = "es"
paginate = 3
canonifyURLs = true
googleAnalytics = ""
enableRobotsTXT = true
