baseURL = 'https://example.org/'
title = "Jairo Flores"
theme = 'ananke'
languageCode = "es"
DefaultContentLanguage = "es"
Paginate = 3
canonifyURLs = true
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/Jairo792"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/jairo-jesus-flores-pereyra-532b45267/?originalSubdomain=bo"
  mastodon = ""
  slack = ""
  codeforces = "https://codeforces.com/profile/newdei"
  stackoverflow = ""
  background_color_class = "bg-black"
  featured_image = "images/jairo.jpg"
  recent_posts_number = 2

# Comentarios adicionales:
# 1. La ruta de 'featured_image' debe ser relativa a la carpeta 'static/'.
# 2. 'Paginate' está configurado para mostrar solo 3 artículos por página.
